dist: trusty
group: edge
language: java
sudo: required
jdk: openjdk8
after_success:
  - mvn jacoco:report coveralls:report
cache:
  directories:
    - /home/lorenzo/.m2
  script:
    - mvn clean install
